ThuVien/Controllers/LibraryStoredController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThuVien.DAL;
using ThuVien.Models;
using ThuVien.ViewModels;

namespace ThuVien.Controllers
{
    public class LibraryStoredController : Controller
    {
        private DB db = new DB();
        private IData data;

        // GET: LibraryStored
        public LibraryStoredController()
        {
            IData _data = data;
        }

        public LibraryStoredController(IData _data)
        {
            this.data = _data;
        }

        public ActionResult Index()
        {
            ViewBag.HK = db.HK.Select(m => new SelectListItem { Text = m.Hocky, Value = m.ID.ToString() });
            return View();
        }

        [HttpPost]
        public ActionResult Index(Step1Model step1)
        {
            if (ModelState.IsValid)
            {
                if (data == null) data = new DataRepository(db);
                Response.Cookies["Step1Cookies"]["HoTen"] = Server.UrlEncode(step1.HoTen);
                Response.Cookies["Step1Cookies"]["SoThe"] = Server.UrlEncode(step1.SoThe);
                Response.Cookies["Step1Cookies"]["Khoa"] = Server.UrlEncode(step1.Khoa);
                Response.Cookies["Step1Cookies"]["DienThoai"] = step1.DienThoai;
                Response.Cookies["Step1Cookies"]["CourseID"] = step1.CourseID;
                Response.Cookies["Step1Cookies"]["TenMon"] = Server.UrlEncode(step1.TenMon);
                Response.Cookies["Step1Cookies"]["Nganh"] = Server.UrlEncode(step1.Nganh);
                Response.Cookies["Step1Cookies"]["Nhom"] = Server.UrlEncode(step1.Nhom);
                Response.Cookies["Step1Cookies"]["HK"] = step1.HK;
                Response.Cookies["Step1Cookies"]["DuTruFrom"] = step1.DuTruFrom.ToString();
                Response.Cookies["Step1Cookies"]["DuTruTo"] = step1.DuTruTo.ToString();
                Response.Cookies["Step1Cookies"]["SoLuongSV"] = step1.SoLuongSV;
                //Response.Cookies["Step1Cookies"].Expires = DateTime.Now.AddDays(1);
                return RedirectToAction("Step2");
            }
            else
            {
                ViewBag.HK = db.HK.Select(m => new SelectListItem { Text = m.Hocky, Value = m.ID.ToString() });
                TempData["data"] = null;
                return View(step1);
            }
        }

        public ActionResult Step2()
        {
            if (Request.Cookies["Step1Cookies"] == null) return RedirectToAction("Index");

            Step2Model model = new Step2Model();
            ViewBag.sId = null;
            ViewBag.tId = null;
            return View(model);
        }

        [HttpPost]
        public ActionResult Step2(Step2Model step2, int sId, int tId, string done)
        {
            Step1Model step1 = new Step1Model();
            if (ModelState.IsValid)
            {
                var from = DateTime.ParseExact(Server.HtmlEncode(Request.Cookies["Step1Cookies"]["DuTruFrom"]), "dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture);
                var to = DateTime.ParseExact(Server.HtmlEncode(Request.Cookies["Step1Cookies"]["DuTruTo"]), "dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture);
                step1.HoTen = Server.UrlDecode(Request.Cookies["Step1Cookies"]["HoTen"]);
                step1.SoThe = Server.UrlDecode(Request.Cookies["Step1Cookies"]["SoThe"]);
                step1.Khoa = Server.UrlDecode(Request.Cookies["Step1Cookies"]["Khoa"]);
                step1.DienThoai = Server.HtmlEncode(Request.Cookies["Step1Cookies"]["DienThoai"]);
                step1.CourseID = Server.HtmlEncode(Request.Cookies["Step1Cookies"]["CourseID"]);
                step1.TenMon = Server.UrlDecode(Request.Cookies["Step1Cookies"]["TenMon"]);
                step1.Nganh = Server.UrlDecode(Request.Cookies["Step1Cookies"]["Nganh"]);
                step1.Nhom = Server.UrlDecode(Request.Cookies["Step1Cookies"]["Nhom"]);
                step1.HK = Server.HtmlEncode(Request.Cookies["Step1Cookies"]["HK"]);
                step1.DuTruFrom = from;
                step1.DuTruTo = to;
                step1.SoLuongSV = Server.HtmlEncode(Request.Cookies["Step1Cookies"]["SoLuongSV"]);

                ////////////////////////////////////////////////////////

                string ReserveType;
                int hk = Int32.Parse(step1.HK);
                var tenHK = db.HK.FirstOrDefault(x => x.STT == hk);

                var MonHoc = new MonHoc()
                {
                    CourseID = step1.CourseID,
                    TenMon = step1.TenMon,
                    Nganh = step1.Nganh,
                    DuTruFrom = step1.DuTruFrom,
                    DuTruTo = step1.DuTruTo,
                    Nhom = step1.Nhom,
                    SoLuongSV = step1.SoLuongSV,
                    HK = tenHK.Hocky
                };

                db.MonHoc.Add(MonHoc);
                db.SaveChanges();

                switch (step2.MucDich)
                {
                    case "0":
                        {
                            ReserveType = "Giáo Trình";
                            break;
                        }
                    case "1":
                        {
                            ReserveType = "Tham Khảo Chính";
                            break;
                        }
                    default:
                        {
                            ReserveType = "Tham Khảo Khác";
                            break;
                        }
                }

                if (tId == 0)
                {
                    switch (sId)
                    {
                        case 0:
                            {
                                var document = new TL_Sach()
                                {
                                    Loai = "Sách",
                                    Nguon = "Thư Viện",
                                    TraCuu = step2.TL_Sach.TraCuu,
                                    ChiTiet = step2.TL_Sach.ChiTiet,
                                    MucDich = ReserveType,
                                    YKien = step2.TL_Sach.YKien,
                                    LanXuatBan = "Không",
                                    NhanDe = "Không",
                                    TacGia = "Không",
                                    NXB = "Không",
                                };

                                if (step2.DangDuTru == "0")
                                {
                                    document.DangDuTru = "Dự trữ dạng giấy";
                                    document.SoLuong = step2.SoLuong;
                                }
                                else
                                {
                                    document.DangDuTru = "Dự trữ dạng điện tử";
                                    document.SoLuong = null;
                                }

                                db.TL_Sach.Add(document);
                                db.SaveChanges();

                                var gv = new GiangVien()
                                {
                                    HoTen = step1.HoTen,
                                    DienThoai = step1.DienThoai,
                                    Khoa = step1.Khoa,
                                    SoThe = step1.SoThe,
                                    MonHocId = MonHoc.ID,
                                    BookId = document.ID
                                };

                                db.GiangVien.Add(gv);

                                break;
                            }
                        case 1:
                            {
                                var document = new TL_Sach()
                                {
                                    Loai = "Sách",
                                    Nguon = "Giảng Viên",
                                    TraCuu = "Không",
                                    NhanDe = step2.TL_Sach.NhanDe,
                                    TacGia = step2.TL_Sach.TacGia,
                                    NXB = step2.TL_Sach.NXB,
                                    LanXuatBan = step2.TL_Sach.LanXuatBan,
                                    MucDich = ReserveType,
                                    ChiTiet = step2.TL_Sach.ChiTiet,
                                    YKien = step2.TL_Sach.YKien
                                };

                                if (step2.DangDuTru == "0")
                                {
                                    document.DangDuTru = "Dự trữ dạng giấy";
                                    document.SoLuong = step2.SoLuong;
                                }
                                else
                                {
                                    document.DangDuTru = "Dự trữ dạng điện tử";
                                    document.SoLuong = null;
                                }

                                db.TL_Sach.Add(document);
                                db.SaveChanges();

                                var gv = new GiangVien()
                                {
                                    HoTen = step1.HoTen,
                                    DienThoai = step1.DienThoai,
                                    Khoa = step1.Khoa,
                                    SoThe = step1.SoThe,
                                    MonHocId = MonHoc.ID,
                                    BookId = document.ID
                                };

                                db.GiangVien.Add(gv);

                                break;
                            }
                        default:
                            {
                                var document = new TL_Sach()
                                {
                                    Loai = "Sách",
                                    Nguon = "Khác",

ThuVien/Views/LibraryStored/Index.cshtml
@model ThuVien.ViewModels.Step1Model
@{
    ViewBag.Title = "Dự trữ tài liệu";
}
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(function () {
            $(".test").datepicker({ dateFormat: "dd/mm/yy" });
        });
    </script>
</head>

<div class="row">
        
    
        @using (Html.BeginForm("Index", "LibraryStored", FormMethod.Post))
        {
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" }) 
            <br />

            <h2>THÔNG TIN GIẢNG VIÊN</h2>
            <div class="row">
                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.HoTen)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.HoTen)
                </div>
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.SoThe)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.SoThe)
                </div>
                @Html.ValidationMessageFor(model => model.SoThe, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.Khoa)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Khoa)
                </div>
                @Html.ValidationMessageFor(model => model.Khoa, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.DienThoai)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.DienThoai)
                </div>
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })

                <br />
                <br />
            </div>

            <div class="row">
                <h2>THÔNG TIN MÔN HỌC</h2>
                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.CourseID)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.CourseID)
                </div>
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.TenMon)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.TenMon)
                </div>
                @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.Nganh)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Nganh)
                </div>
                @Html.ValidationMessageFor(model => model.Nganh, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.Nhom)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Nhom)
                </div>
                @Html.ValidationMessageFor(model => model.Nhom, "", new { @class = "text-danger", @type = "number" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.HK)
                </div>

                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.HK, (IEnumerable<SelectListItem>)ViewBag.HK, "--Vui lòng chọn--", new { @class = "selectionType", onchange = "SelectType()" })
                </div>
                @Html.ValidationMessageFor(model => model.HK, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.DuTruFrom)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.DuTruFrom, "{0:dd/MM/yyyy}", new { @class = "test" })
                </div>
                @Html.ValidationMessageFor(model => model.DuTruFrom, "", new { @class = "text-danger" })

                <br />
                <br />

                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.DuTruTo)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.DuTruTo, "{0:dd/MM/yyyy}", new { @class = "test" })
                </div>
                @Html.ValidationMessageFor(model => model.DuTruTo, "", new { @class = "text-danger" })

                <br />
                <br />
                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.SoLuongSV)
                </div>

                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.SoLuongSV)
                </div>

                <br />
                <br />
                <input type="submit" value="Tiếp Tục" />
            </div>
        }
            
</div>